In [10]:
import pandas as pd

# Series: 1차원 데이터
# 가로로 뻗어나가는 축 하나: axis 0

s1 = pd.Series([5000, 30000, 20000, 15000])
display(s1)

print("-" * 40)

s2 = pd.Series({\
    "2020-03-03": 5000, "2020-03-04": 30000,\
    "2020-03-05": 20000, "2020-03-06": 15000
})
display(s2)

print("-" * 40)

# 데이터와 인덱스를 통으로 입력
s3 = pd.Series([5000, 30000, 20000, 15000],\
               index=["2020-03-03", "2020-03-04", "2020-03-05", "2020-03-06"],
               name="durian")
s3.index.name = "dates"

# 상동
s3 = pd.Series([5000, 30000, 20000, 15000])
# attribute로 접근
s3.index = ("2020-03-03", "2020-03-04", "2020-03-05", "2020-03-06")
s3.name = "durian"
display(s3)

print("-" * 40)

s = pd.Series([1, 2, 3, 4, 5])
display(s)
display(s.values)
display(s.index)

0     5000
1    30000
2    20000
3    15000
dtype: int64

----------------------------------------

2020-03-03     5000
2020-03-04    30000
2020-03-05    20000
2020-03-06    15000
dtype: int64

----------------------------------------

2020-03-03     5000
2020-03-04    30000
2020-03-05    20000
2020-03-06    15000
Name: durian, dtype: int64

----------------------------------------

0    1
1    2
2    3
3    4
4    5
dtype: int64

array([1, 2, 3, 4, 5])

RangeIndex(start=0, stop=5, step=1)

In [8]:

df2 = pd.DataFrame([
    [4000, 20000, 10000],
    [5000, 8000, 11000],
    [6000, 9000, 12000]
])
df2.index = [[
    "apple",
    "banana",
    "cherry"
]]
df2.columns = [["03.03", "03.04", "03.05"]]
display(df2)

print("-" * 40)
print("시리즈를 합친 것이 데이터프레임")
s1 = pd.Series(
    [4000, 20000, 10000],
    index=["03.03", "03.04", "03.05"],
    name="apple"
)
s2 = pd.Series(
    [5000, 8000, 11000],
    index=["03.03", "03.04", "03.05"],
    name="banana"
)
s3 = pd.Series(
    [6000, 9000, 12000],
    index=["03.03", "03.04", "03.05"],
    name="cherry"
)
dataframe_from_series = pd.DataFrame([s1, s2, s3])
display(dataframe_from_series)

       03.03  03.04  03.05
apple   4000  20000  10000
banana  5000   8000  11000
cherry  6000   9000  12000

----------------------------------------
시리즈를 합친 것이 데이터프레임

        03.03  03.04  03.05
apple    4000  20000  10000
banana   5000   8000  11000
cherry   6000   9000  12000

In [12]:
df = pd.DataFrame({
    "2020-03-03": [4000, 20000, 10000],
    "2020-03-04": [5000, 8000, 11000],
    "2020-03-05": [6000, 9000, 12000],
    },
    index=["apple", "banana", "cherry"]
)
display(df)
print("-" * 40)

# 2차원 데이터 조회
df["2020-03-03"]
df.loc["banana"]
df.loc[df["2020-03-03"]>4000,:]

        2020-03-03  2020-03-04  2020-03-05
apple         4000        5000        6000
banana       20000        8000        9000
cherry       10000       11000       12000

----------------------------------------

        2020-03-03  2020-03-04  2020-03-05
banana       20000        8000        9000
cherry       10000       11000       12000

In [17]:
import pandas as pd
import numpy as np

lines = [
    '1997,Ford,E350,"ac, abs, moon",3000.00',
    '1999,Chevy,"Venture ""Extended Edition""","",4900.00',
    '1999,Chevy,"Venture ""Extended Edition, Very Large""",,5000.00',
    '1996,Jeep,Grand Cherokee,"MUST SELL! air, moon roof, loaded",4799.00"'
]
with open("./dataset-no-column.csv", "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

data = pd.read_csv("./dataset-no-column.csv")  # read_csv는 첫 줄을 헤더로 간주함
display(data)

data = pd.read_csv("./dataset-no-column.csv",
                   header=None)  # 헤더 없이 -> 임의의 헤더
display(data)

df = pd.DataFrame(np.random.randn(10, 4), columns=["A", "B", "C", "D"])
display(df)

df.to_csv("./result2.csv")

,1997,Ford,E350,"ac, abs, moon",3000.00
0,1999,Chevy,"Venture ""Extended Edition""",NaN,4900.00
1,1999,Chevy,"Venture ""Extended Edition, Very Large""",NaN,5000.00
2,1996,Jeep,Grand Cherokee,"MUST SELL! air, moon roof, loaded","4799.00"""

,0,1,2,3,4
0,1997,Ford,E350,"ac, abs, moon",3000.00
1,1999,Chevy,"Venture ""Extended Edition""",NaN,4900.00
2,1999,Chevy,"Venture ""Extended Edition, Very Large""",NaN,5000.00
3,1996,Jeep,Grand Cherokee,"MUST SELL! air, moon roof, loaded","4799.00"""

          A         B         C         D
0 -1.416380  0.080680 -0.159099  0.030575
1  2.238605  0.711450  0.243825  0.142340
2 -1.287963  0.207499 -1.752081 -2.025903
3 -0.484833 -0.665985 -2.427215 -0.036988
4 -0.787299 -0.176542 -0.051214 -0.346898
5 -0.688249  0.594098 -0.916209 -1.068084
6  1.647652  0.011891  0.249915  0.797895
7 -0.677982  0.788826 -1.086406  1.156669
8 -1.055862  1.570428  0.487089  1.170241
9 -0.904064  0.341165 -0.770454 -0.005600

In [24]:
# https://blog.naver.com/youji4ever/221712578078

dates = pd.date_range("20130101", periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
display(df)

print("-" * 40)

# reindex(재 인덱스)는 해당 축에 대하여 인덱스를 변경/추가/삭제
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["E"])
df1.loc[dates[0]:dates[1], "E"] = 1
display(df1)

print("-" * 40)

display(pd.isna(df1))
display(df1.dropna(how="any"))
display(df1.fillna(value=5))

                   A         B         C         D
2013-01-01 -1.219629 -1.583763  1.420570  0.625369
2013-01-02 -0.387243  0.594953 -2.172567  0.992849
2013-01-03  1.504893 -0.061896  1.285915 -0.079966
2013-01-04  0.324647 -0.158408 -1.279401  1.958919
2013-01-05  0.770668  0.957162 -0.868243  1.143829
2013-01-06 -0.366379  0.706350  0.045724  0.375169

----------------------------------------

                   A         B         C         D    E
2013-01-01 -1.219629 -1.583763  1.420570  0.625369  1.0
2013-01-02 -0.387243  0.594953 -2.172567  0.992849  1.0
2013-01-03  1.504893 -0.061896  1.285915 -0.079966  NaN
2013-01-04  0.324647 -0.158408 -1.279401  1.958919  NaN

----------------------------------------

                A      B      C      D      E
2013-01-01  False  False  False  False  False
2013-01-02  False  False  False  False  False
2013-01-03  False  False  False  False   True
2013-01-04  False  False  False  False   True

                   A         B         C         D    E
2013-01-01 -1.219629 -1.583763  1.420570  0.625369  1.0
2013-01-02 -0.387243  0.594953 -2.172567  0.992849  1.0

                   A         B         C         D    E
2013-01-01 -1.219629 -1.583763  1.420570  0.625369  1.0
2013-01-02 -0.387243  0.594953 -2.172567  0.992849  1.0
2013-01-03  1.504893 -0.061896  1.285915 -0.079966  5.0
2013-01-04  0.324647 -0.158408 -1.279401  1.958919  5.0

In [28]:
df1 = pd.DataFrame({
    "Favorite Food": [
        "Alfredo Pasta",
        "Bobba",
        "Croissants",
        "Danish Rolls",
        "Edaame",
        "Fish",
        "Ice Cream"
    ]
    },
        index=pd.Index(["Alfred", "Bob", "Cris", "Daniel", "Edward", "Fitz", "Ivan"],
        name="Name"),
)
df2 = pd.DataFrame({
    "Favorite Country": [
        "Albania",
        "Croatia",
        "Denmark",
        "Fiji",
        "Germany",
        "Haiti"
    ]},
    index=pd.Index(["Alfred", "Cris", "Daniel", "Fitz", "Gerald", "Hayden"],
    name="Name"),
)
display(df1)
display(df2)
print("-" * 40)

# axis가 없으면: 세로로 길쭉하게 합치기
display(pd.concat([df1, df2], sort=False))  # concat 사용 <- append는 pandas 2.0부터 deprecated

        Favorite Food
Name
Alfred  Alfredo Pasta
Bob             Bobba
Cris       Croissants
Daniel   Danish Rolls
Edward         Edaame
Fitz             Fish
Ivan        Ice Cream

       Favorite Country
Name
Alfred          Albania
Cris            Croatia
Daniel          Denmark
Fitz               Fiji
Gerald          Germany
Hayden            Haiti

----------------------------------------

        Favorite Food Favorite Country
Name
Alfred  Alfredo Pasta              NaN
Bob             Bobba              NaN
Cris       Croissants              NaN
Daniel   Danish Rolls              NaN
Edward         Edaame              NaN
Fitz             Fish              NaN
Ivan        Ice Cream              NaN
Alfred            NaN          Albania
Cris              NaN          Croatia
Daniel            NaN          Denmark
Fitz              NaN             Fiji
Gerald            NaN          Germany
Hayden            NaN            Haiti

In [29]:
display(pd.concat([df1, df2], axis=1, sort=False))  # axis=1 -> 열 추가(옆으로 붙이기)

        Favorite Food Favorite Country
Name
Alfred  Alfredo Pasta          Albania
Bob             Bobba              NaN
Cris       Croissants          Croatia
Daniel   Danish Rolls          Denmark
Edward         Edaame              NaN
Fitz             Fish             Fiji
Ivan        Ice Cream              NaN
Gerald            NaN          Germany
Hayden            NaN            Haiti

In [30]:
display(pd.concat([df1, df2], axis=1, sort=True))  # Fitz 다음 Gerald, Hayden, Ivan 순으로 정렬됐다

        Favorite Food Favorite Country
Name
Alfred  Alfredo Pasta          Albania
Bob             Bobba              NaN
Cris       Croissants          Croatia
Daniel   Danish Rolls          Denmark
Edward         Edaame              NaN
Fitz             Fish             Fiji
Gerald            NaN          Germany
Hayden            NaN            Haiti
Ivan        Ice Cream              NaN

In [ ]:
# https://school.programmers.co.kr/learn/courses/30/lessons/181924?language=python3

def solution(arr: list[int], queries: list[list[int, int]]) -> list[int]:
    answer = []

    for i in range(len(queries)):
        first_query, second_query = queries[i]

        arr[first_query], arr[second_query] = arr[second_query], arr[first_query]

    return answer