In [6]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame({
    "Favorite Food": [
        "Alfredo Pasta",
        "Bobba",
        "Croissants",
        "Danish Rolls",
        "Edaame",
        "Fish",
        "Ice Cream"
    ]
},
    index=pd.Index(["Alfred", "Bob", "Cris", "Daniel", "Edward", "Fitz", "Ivan"],
                   name="Name"),
)
df2 = pd.DataFrame({
    "Favorite Country": [
        "Albania",
        "Croatia",
        "Denmark",
        "Fiji",
        "Germany",
        "Haiti"
    ]},
    index=pd.Index(["Alfred", "Cris", "Daniel", "Fitz", "Gerald", "Hayden"],
                   name="Name"),
)
display(df1)
display(df2)
print("-" * 40)

        Favorite Food
Name
Alfred  Alfredo Pasta
Bob             Bobba
Cris       Croissants
Daniel   Danish Rolls
Edward         Edaame
Fitz             Fish
Ivan        Ice Cream

       Favorite Country
Name
Alfred          Albania
Cris            Croatia
Daniel          Denmark
Fitz               Fiji
Gerald          Germany
Hayden            Haiti

----------------------------------------
outer join - 합집합

        Favorite Food Favorite Country
Name
Alfred  Alfredo Pasta          Albania
Bob             Bobba              NaN
Cris       Croissants          Croatia
Daniel   Danish Rolls          Denmark
Edward         Edaame              NaN
Fitz             Fish             Fiji
Gerald            NaN          Germany
Hayden            NaN            Haiti
Ivan        Ice Cream              NaN

inner join - 교집합

        Favorite Food Favorite Country
Name
Alfred  Alfredo Pasta          Albania
Cris       Croissants          Croatia
Daniel   Danish Rolls          Denmark
Fitz             Fish             Fiji

기본값 - left join

        Favorite Food Favorite Country
Name
Alfred  Alfredo Pasta          Albania
Bob             Bobba              NaN
Cris       Croissants          Croatia
Daniel   Danish Rolls          Denmark
Edward         Edaame              NaN
Fitz             Fish             Fiji
Ivan        Ice Cream              NaN

right join

        Favorite Food Favorite Country
Name
Alfred  Alfredo Pasta          Albania
Cris       Croissants          Croatia
Daniel   Danish Rolls          Denmark
Fitz             Fish             Fiji
Gerald            NaN          Germany
Hayden            NaN            Haiti

In [7]:

print("outer join - 합집합")
display(df1.join(df2, how="outer"))

print("inner join - 교집합")
display(df1.join(df2, how="inner"))

print("기본값 - left join")
display(df1.join(df2))

print("right join")
display(df1.join(df2, how="right"))

outer join - 합집합

        Favorite Food Favorite Country
Name
Alfred  Alfredo Pasta          Albania
Bob             Bobba              NaN
Cris       Croissants          Croatia
Daniel   Danish Rolls          Denmark
Edward         Edaame              NaN
Fitz             Fish             Fiji
Gerald            NaN          Germany
Hayden            NaN            Haiti
Ivan        Ice Cream              NaN

inner join - 교집합

        Favorite Food Favorite Country
Name
Alfred  Alfredo Pasta          Albania
Cris       Croissants          Croatia
Daniel   Danish Rolls          Denmark
Fitz             Fish             Fiji

기본값 - left join

        Favorite Food Favorite Country
Name
Alfred  Alfredo Pasta          Albania
Bob             Bobba              NaN
Cris       Croissants          Croatia
Daniel   Danish Rolls          Denmark
Edward         Edaame              NaN
Fitz             Fish             Fiji
Ivan        Ice Cream              NaN

right join

        Favorite Food Favorite Country
Name
Alfred  Alfredo Pasta          Albania
Cris       Croissants          Croatia
Daniel   Danish Rolls          Denmark
Fitz             Fish             Fiji
Gerald            NaN          Germany
Hayden            NaN            Haiti

In [10]:
# merge - join 기능으로부터 더욱 보강한 것

# merge를 사용하기 전엔 reset_index를 먼저 실행해야 한다
df1 = df1.reset_index()
df2 = df2.reset_index()
display(df1)
display(df2)

# 교집합(inner)가 기본값. how=에다가 "outer", "left", "right" 선택 가능
display(pd.merge(df1, df2))

display(df1.merge(df2))

df3 = pd.DataFrame({"Favorite Course": ["Criminomogy", "Design", "Fitness"],
                    "Favorite Country": ["Croatia", "Denmark", "Fiji"]})

display(pd.merge(df2, df3))

   index    Name  Favorite Food
0      0  Alfred  Alfredo Pasta
1      1     Bob          Bobba
2      2    Cris     Croissants
3      3  Daniel   Danish Rolls
4      4  Edward         Edaame
5      5    Fitz           Fish
6      6    Ivan      Ice Cream

   index    Name Favorite Country
0      0  Alfred          Albania
1      1    Cris          Croatia
2      2  Daniel          Denmark
3      3    Fitz             Fiji
4      4  Gerald          Germany
5      5  Hayden            Haiti

   index    Name  Favorite Food Favorite Country
0      0  Alfred  Alfredo Pasta          Albania

   index    Name  Favorite Food Favorite Country
0      0  Alfred  Alfredo Pasta          Albania

   index    Name Favorite Country Favorite Course
0      1    Cris          Croatia     Criminomogy
1      2  Daniel          Denmark          Design
2      3    Fitz             Fiji         Fitness

In [12]:
df4 = pd.DataFrame({"Name": ["Cris", "Daniel", "Fitz", "Peter"],
                    "Favorite Country": ["Croatia", "Denmark", "Fiji", "Croatia"],
                    "Favorite Course": ["Criminomogy", "Design", "Fitness", "Yoga"]})

display(df2)
display(df4)

print("on은 기준컬럼")
display(df2.merge(df4, on=["Favorite Country"]))

   index    Name Favorite Country
0      0  Alfred          Albania
1      1    Cris          Croatia
2      2  Daniel          Denmark
3      3    Fitz             Fiji
4      4  Gerald          Germany
5      5  Hayden            Haiti

     Name Favorite Country Favorite Course
0    Cris          Croatia     Criminomogy
1  Daniel          Denmark          Design
2    Fitz             Fiji         Fitness
3   Peter          Croatia            Yoga

on은 기준컬럼

   index  Name_x Favorite Country  Name_y Favorite Course
0      1    Cris          Croatia    Cris     Criminomogy
1      1    Cris          Croatia   Peter            Yoga
2      2  Daniel          Denmark  Daniel          Design
3      3    Fitz             Fiji    Fitz         Fitness

In [14]:
# 강의교안 p.33

df = pd.DataFrame({"name": ["one", "one", "one", "two", "two", "two"],
                   "grade": ["A", "B", "C", "A", "B", "C"],
                   "score": [1, 2, 3, 4, 5, 6],
                   "class": ["x", "y", "z", "q", "w", "t"]
                   })
display(df)

print("피벗")
display(df.pivot(index="name", columns="grade", values="score"))

print("-" * 40)

df3 = pd.DataFrame({"first": ["John", "Mary"],
                    "last": ["Doe", "Bo"],
                    "height": [5.5, 6.0],
                    "weight": [130, 150]})
display(df3)

print("melt")
display(df3.melt(id_vars=["first", "last"]))

  name grade  score class
0  one     A      1     x
1  one     B      2     y
2  one     C      3     z
3  two     A      4     q
4  two     B      5     w
5  two     C      6     t

피벗

grade  A  B  C
name
one    1  2  3
two    4  5  6

----------------------------------------

  first last  height  weight
0  John  Doe     5.5     130
1  Mary   Bo     6.0     150

melt

  first last variable  value
0  John  Doe   height    5.5
1  Mary   Bo   height    6.0
2  John  Doe   weight  130.0
3  Mary   Bo   weight  150.0

In [17]:
print("stack / unstack")

index = pd.MultiIndex.from_tuples([("bar", "one"), ("bar", "two"),
                                   ("baz", "one"), ("baz", "two")],
                                  names=["class", "name"])
df2 = pd.DataFrame([[1, 2], [3, 4], [5, 6], [7, 8]], index=index, columns=["eng", "math"])
display(df2)

stacked = df2.stack()
display(stacked)

print("stacked.index.names: ", stacked.index.names)

print("unstack")
display(stacked.unstack())

print(stacked.unstack().index.names)
display(stacked.unstack("name"))  # 또는 stacked.unstack(1)
display(stacked.unstack("class"))  # 또는 stacked.unstack(0)

stack / unstack

            eng  math
class name
bar   one     1     2
      two     3     4
baz   one     5     6
      two     7     8

class  name
bar    one   eng     1
             math    2
       two   eng     3
             math    4
baz    one   eng     5
             math    6
       two   eng     7
             math    8
dtype: int64

stacked.index.names:  ['class', 'name', None]
unstack

            eng  math
class name
bar   one     1     2
      two     3     4
baz   one     5     6
      two     7     8

['class', 'name']

name        one  two
class
bar   eng     1    3
      math    2    4
baz   eng     5    7
      math    6    8

class      bar  baz
name
one  eng     1    5
     math    2    6
two  eng     3    7
     math    4    8

In [ ]:
class Pet:
    all = []

    def __init__(self, name):
        self.name = name
        self.hunger = 5
        Pet.all.append(self)

    def feed(self):
        self.hunger -= 1

    @classmethod
    def to_df(cls):
        return pd.DataFrame({"이름": p.name, "배고픔": p.hunger} for p in cls.all)

In [23]:
class Movie:
    def __init__(self, name = "odyssey", time = "day"):
        self.name = name
        self.time = time

    def show_name(self):
        print(self.name)

    def show_time(self):
        print(self.time)


class Theater:
    def __init__(self, name, type="normal"):
        self.name = name
        self.type = type

    def show_name(self):
        print(self.name)

    def room_type(self):
        print(self.type)

    def ticket(self):
        pass


class Ticket(Movie, Theater):
    """
    상영관
    좌석
    종류: 일반/VIP
    """
    pass


class Person(Movie, Theater):
    def __init__(self):
        pass


odyssey = Movie("odyssey")
iliad = Movie("iliad")
homer = Movie("homer")

odyssey.show_name()
iliad.show_name()
homer.show_name()

print("-" * 40)

t1 = Theater("상영관 1", "일반")
t2 = Theater("상영관 2", "VIP")

t1.room_type()
t2.room_type()

odyssey
iliad
homer
----------------------------------------
일반
VIP